### ISSUE TITLE
osc_callbacks issue at line 17

### ISSUE THREAD

**Issue by alucula** [BarakChamo/TD_PoseNet#4]
![Screenshot 2020-05-11 at 12 37 51](https://user-images.githubusercontent.com/23052761/81557797-79674a80-9384-11ea-9d18-a6357142a5e0.png)
Thank you very much for sharing this project on github! I managed to set up the osc connection but can't get over the osc_callbacks DAT. Does anyone know a way to solve this?
Thank you in advance

**Comment by JeremyKeenan** [comment]
Any update on this? I'm having the same issue...

**Comment by ronansomerville** [comment]
Need help on this one aswell, any answers?

**Comment by alucula** [comment]
Hi I found a workaround to make poseNet communicating with TD using SocketIO which I believe it was from a class of the immersive&interactiveHQ if it could help

**Comment by ronansomerville** [comment]
> Hi I found a workaround to make poseNet communicating with TD using SocketIO which I believe it was from a class of the immersive&interactiveHQ if it could help

That would be so helpful! If you could share that would be great

**Comment by alucula** [comment]
https://github.com/alucula/PoseNet-Touchdesigner
